### ISSUE TITLE
PHP 7.2: Replace Nette\Object by Nette\SmartObject please

### ISSUE THREAD

**Issue by dada-amater** [Kdyby/Wkhtmltopdf#9]
Can you please replace Nette\Object by Nette\SmartObject ? This blocks us from upgrading to php 7.2

**Comment by enumag** [comment]
See https://github.com/Kdyby/Wkhtmltopdf/pull/8. If you could test that branch on your project it would be great!

**Comment by dada-amater** [comment]
Thank you, I will try it. If I find any bug, I will let you know.
